apiVersion: v1
kind: Pod
metadata:
  name: view
  labels:
    name: view   
spec:
  containers:
  - command:
    - /usr/local/bin/start_terrama2_service.sh
    - VIEW
    - "6545"
    image: terrama2/terrama2:4.0.11
    name: view
    resources: {}
    tty: true
    volumeMounts:
    - mountPath: /data
      name: repositorie-data
    - mountPath: /shared-data
      name: repositorie-data
  restartPolicy: Always
  volumes:
    - name: repositorie-data
      persistentVolumeClaim:
        claimName: repositorie-data-claim
status: {}
