apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    name: webapp   
spec:
  containers:
  - image: terrama2/terrama2-webapp:4.0.11
    name: webapp
    ports:
    - containerPort: 36000
    resources: {}
    volumeMounts:
    - mountPath: /opt/terrama2/4.0.11/webapp/config/instances/
      name: webapp-config
    - mountPath: /root/
      name: pgpass-config
    - mountPath: /data
      name: repositorie-data
    - mountPath: /shared-data
      name: repositorie-data
  restartPolicy: Always
  volumes:
    - name: repositorie-data
      persistentVolumeClaim:
        claimName: repositorie-data-claim
    - name: pgpass-config
      configMap:
        name: pgpass-config
    - name: webapp-config
      configMap:
          name: webapp-config
status: {}
